---
apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    author: nagarjuna
spec:
  type: load Balncer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
  selector:
    name: result-app
...