---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    name: voting-app
    author: nagarjuna
spec:
  type: load Balancer
  ports:
    -
      targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    name: voting-app
...